server:
  port: 1001
spring:
  application:
    name: gateway

#  cloud:
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password: 123456
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: root
#    password: root
#    virtual-host: /power-shop
#    nacos:
#      # 注册中心配置
#      discovery:
#        server-addr: localhost:8848
#        namespace: 3e80eea2-78db-47c1-b674-c370266eafe1
#        username: nacos
#        password: nacos
#        group: DEFAULT_GROUP
#    # 网关配置信息
#    gateway:
#      discovery:
#        locator:
#          # 通过动态路由访问
#          enabled: true
#          # 忽略大小写，所有微服务id小写
#          lower-case-service-id: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

