server:
  port: 20001
spring:
  application:
    name: eureka-client-a
  cloud:
      inetutils:
        ignoredInterfaces:
          - VMware.* # 忽略虚拟机网卡
        use-only-site-local-interfaces: true
        preferred-networks: 192.168.50.* # 优先使用 192.168.50.*
eureka:
  client:
    service-url:
      #单机注册
      #defaultZone: http://localhost:10001/eureka
      #集群注册
      defaultZone: http://localhost:10001/eureka, http://localhost:10002/eureka, http://localhost:10003/eureka
