server:
  port: 20002
spring:
  application:
    name: eureka-client-b
  cloud:
    inetutils:
      ignoredInterfaces:
        - VMware.* # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.50.* # 优先使用 192.168.50.*
  #数据源连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      #单机注册
      #defaultZone: http://localhost:10001/eureka
      #集群注册
      defaultZone: http://localhost:10001/eureka, http://localhost:10002/eureka, http://localhost:10003/eureka
  instance:
    # 是否使用ip地址注册
    prefer-ip-address: true