# 配置运行的端口号
server:
  port: 10002
spring:
  application:
    # 注册到注册中心的微服务的名称
    name: eureka-server-02
  cloud:
    inetutils:
      ignoredInterfaces:
        - VMware.* # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.50.* # 优先使用 192.168.50.*
# Eureka配置信息
eureka:
  # Eureka的客户端配置
  # 由于Eureka搭建服务器端的集群，它们之间的节点需要相互注册，我们也可以将运行的Eureka服务器端看作成一个客户端
  client:
    # 注册的服务地址，注册中心的地址
    service-url:
      # 注册中心的地址
      # 在浏览器访问时，不需要待eureka的项目名称，直接访问http://localhost:1001/
      #defaultZone: http://localhost:1002/eureka
      # http://eureka1001/eureka,http://eureka1002/eureka
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka10005:10002/eureka,http://eureka10004:10004/eureka}
    # 是否拉取服务列表，false代表不拉取服务列表，默认为true
    fetch-registry: true
    # 是否注册到注册中心中，false代表不注册，默认为true
    register-with-eureka: true

