server:
  port: 20001
spring:
  application:
    name: nacos-client-b
    #数据源连接信息
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/crm?characterEncoding=UTF-8
#    username: root
#    password: 123456
#  cloud:
#    nacos:
#      #Nacos的注册地址
#      server-addr: localhost:8848
#      discovery:
#        username: nacos
#        password: nacos
#        group: DEFAULT_GROUP
#        #必须注册到同一个命名空间下才可以进行远程调用
#        #如果不小心注册到了其他命名空间中，无法进行远程调用，因为每个命名空间都是独立的，隔离的
#        namespace: 8283ff35-e41a-40f8-92cf-3088fceeaa1e